// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Comment

package model

// CommentSlice is a slice of type Comment. Use it where you would use []Comment.
type CommentSlice []Comment

// SelectUint32 projects a slice of uint32 from CommentSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv CommentSlice) SelectUint32(fn func(Comment) uint32) (result []uint32) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
