// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Thread

package model

// ThreadSlice is a slice of type Thread. Use it where you would use []Thread.
type ThreadSlice []Thread

// SelectUint32 projects a slice of uint32 from ThreadSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv ThreadSlice) SelectUint32(fn func(Thread) uint32) (result []uint32) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}
