// Generated by: gen
// TypeWriter: slice
// Directive: +gen on User

package model

// UserSlice is a slice of type User. Use it where you would use []User.
type UserSlice []User

// SelectUint32 projects a slice of uint32 from UserSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv UserSlice) SelectUint32(fn func(User) uint32) (result []uint32) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}

// GroupByUint32 groups elements into a map keyed by uint32. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv UserSlice) GroupByUint32(fn func(User) uint32) map[uint32]UserSlice {
	result := make(map[uint32]UserSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}
